baseURL = "https://follow.almujahidinmosque.or.id/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Tautan Bio | Al-Mujahidin Mosque"
copyright = "2020-2023 | Al-Mujahidin Mosque"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Al-Mujahidin Mosque"
  image = "image/logo-web.webp"

  links = [
    { link = { href = "https://almujahidinmosque.or.id", text = "Website", target = "_blank" } },
    { google = { href = "https://goo.gl/maps/dWWYDN1gMqPyj1s8A", text = "Maps", target = "_blank" } },
    { facebook = { href = "https://facebook.com/almujahidinmosque", text = "Facebook", target = "_blank" } },
    { instagram = { href = "https://instagram.com/almujahidinmosque", text = "Instagram", target = "_blank" } },
    { tiktok = { href = "https://tiktok.com/@almujahidinmosque", text = "TikTok", target = "_blank" } },
    { twitter = { href = "https://twitter.com/almujahidinmsq", text = "Twitter", target = "_blank" } },
    { github = { href = "https://github.com/almujahidinmosque", text = "GitHub", target = "_blank" } },
    { email = { href = "mailto:almujahidinmosque.or.id@gmail.com", text = "Email", target = "_blank" } },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { google = "https://www.google.com/" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { youtube = "https://youtube.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.86.1"
